/*
    Logan Murray
    CSC 355 - 502
    02-11-2019
    Assignment 4
*/

-- Query 1
    SELECT FirstName, LastName FROM EMPLOYEE 
        WHERE SUPERVISORID IN (Select ID from EMPLOYEE WHERE GENDER = 'M');
-- Query 2
    SELECT cast(AVG(Salary) as decimal(19,2)) as "AVG SALARY" FROM EMPLOYEE, DEPARTMENT 
        WHERE DNAME = 'Engineering';
-- Query 3
    SELECT DISTINCT(LastName), EMPLOYEE.ID, PLocation FROM EMPLOYEE, PROJECT, ASSIGNMENT 
        WHERE PLocation = 'Chicago' ORDER BY LastName;
-- Query 4
    SELECT DISTINCT(PNumber), PName, SUM(Hours) AS "TOTAL HOURS" FROM PROJECT FULL OUTER JOIN ASSIGNMENT 
        ON ASSIGNMENT.PNO = PROJECT.PNUMBER 
        group by (PNumber), PName ORDER BY "TOTAL HOURS" DESC NULLS LAST;
-- Query 5
    SELECT DISTINCT(ID) FROM (SELECT ID, COUNT(PNO) AS "COUNT" FROM ASSIGNMENT, EMPLOYEE
         WHERE(EMPLOYEE.ID = ASSIGNMENT.EID) group by ID) WHERE COUNT >= 3;
-- Query 6
    SELECT DISTINCT(DNO) AS "DEPT_NUM", COUNT(EMPLOYEE.DNO) AS "NUM_EMPLOYEES", MAX(EMPLOYEE.SALARY) AS "HIGHEST_SAL" 
        FROM DEPARTMENT, EMPLOYEE
            WHERE DEPARTMENT.DNUMBER = EMPLOYEE.DNO 
            group by (DNO) ORDER BY "NUM_EMPLOYEES";
-- Query 7 
    SELECT EMPLOYEE.FIRSTNAME, EMPLOYEE.LASTNAME FROM EMPLOYEE, DEPENDENT 
        WHERE EMPLOYEE.ID = DEPENDENT.EID 
        AND DEPENDENT.RELATIONSHIP = 'Spouse' 
        AND EMPLOYEE.GENDER = 'F'
        ORDER BY FIRSTNAME; 
-- Query 8 
    SELECT EMPLOYEE.FIRSTNAME, EMPLOYEE.SALARY FROM EMPLOYEE, PROJECT, ASSIGNMENT 
        WHERE EMPLOYEE.ID = ASSIGNMENT.EID 
        AND ASSIGNMENT.PNO = PROJECT.PNUMBER
        AND ASSIGNMENT.PNO = (SELECT Pnumber FROM PROJECT WHERE Pname = 'Public Relations')
        AND ASSIGNMENT.HOURS >= 15;